[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

lib_ldf_mode = chain+
lib_extra_dirs = ../..

; Configuración del compilador
; Include paths relativos desde examples/self_check/
build_flags = 
    -I../../src


